### ISSUE TITLE
error on query.get_field_mapping()

### ISSUE THREAD

**Issue by SFXShannon** [samw1989/my-quickbase#1]
self.field_mapping = {str(field_dict['id']): field_dict['label'] for field_dict in parse_response(response)}
TypeError: string indices must be integers

**Comment by samw1989** [comment]
Hello, I managed to replicate this by deliberately entering incorrect argument values for the app and/or table IDs. 

You may want to double check those are correct - you can find the relevant information in the 'Show Support Information' in the main settings page (accessible from the home page of your app)

I believe both IDs are always 9 digits long.

In addition, perhaps (if you haven't done already) try just establishing an AppQuery instance, to make sure the appID is indeed correct:

```
import my_quickbase as mq
query = mq.AppQuery(app_id="_enterappIDhere_")
query.get_tables()
```

If this last line returns:
`{'message': 'Invalid request', 'description': 'The appId/tableId is not valid.'}`

...then you'll know there's a problem with the appID. If not, then I'm fairly certain it'll be an issue with the tableID you entered.

In the meantime, I had intended to raise an exception when this happens, which will pinpoint the reason for the error. I will fix this and update the package very soon.

**Comment by samw1989** [comment]
Update to code made. 0.2.1 now released.
